databases:
  - name: seni
    databaseName: seni
    user: intervention_user

services:
  - type: web
    name: intervention-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && python create_superuser.py"
    startCommand: "gunicorn intervention_management.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seni
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"  # Personnalise selon tes besoins
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"  # Personnalise selon tes besoins
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "adminpassword"  # Personnalise selon tes besoins (garde-le sécurisé)