# Generated by Django 5.1.6 on 2025-03-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_emission', models.DateField()),
                ('date_max_realisation', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse_intervention', models.TextField()),
                ('adresse_bailleur', models.TextField()),
                ('nom_bailleur', models.CharField(max_length=100)),
                ('nom_prenom_locataire', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('nombre_passages', models.PositiveIntegerField()),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('rapport_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.intervention')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='type_prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeintervention'),
        ),
    ]
